whithout check ships position
mate-academy/py-battleship pull request #91
Opened 2022-11-22 14:36 UTC by bythewaters

2022-11-23 09:57 UTC, Abnormaltype requested changes

2022-11-23 09:57 UTC, Abnormaltype commented on app/main.py
> +    pass
use correct naming for `Errors`

2022-11-23 09:57 UTC, Abnormaltype commented on app/main.py
> +            else:
unnecessary else

2022-11-24 09:06 UTC, Abnormaltype requested changes

2022-11-24 09:06 UTC, Abnormaltype commented on app/main.py
> +class NumberOfShipsDeck(Exception):
```suggestion
class NumberOfShipsDeckError(Exception):
```

2022-11-24 09:06 UTC, Abnormaltype commented on app/main.py
> +class TotalNumberOfTheShips(Exception):
```suggestion
class TotalNumberOfTheShipsError(Exception):
```

2022-11-24 13:47 UTC, YuriiKindrat approved these changes

2024-06-10 16:56 UTC, closed without merging